### ISSUE TITLE
Implement "my favourites" functionality

### ISSUE THREAD

**Issue by tomekz** [tomekz/viennaBike-native#4]
Implement "my favourites" functionality that comprises off:
- new "my favourites" screen listing stations favoured by the user
- add fav star/button allowing user to add/remove this station to favourites list to the `components\StationCard`
- persist the list in AsyncStorage

**Comment by myin142** [comment]
I am currently trying to implement this. But I do not know how to toggle the favorite icon when it is clicked on. It can add/remove the station but it does not change the icon in realtime.

Do you have any idea how to achieve this?

**Comment by tomekz** [comment]
Great, 
Just so you know I updated the feature requirements a bit not having to rely on `react-native-maps` <Marker/> and <Callout/> components since they are really unstable and have many cross-devices issues in the version being used.

So with the new approach I would just simply add fav star icon/button to the `components\StationCard` left aligned below the station logo. Then the changes in the component would go sth like this

- add new local state variable
- add toggleFav function 
```
toggleFav () {
        this.setState((prevState) => {
            return {
                isFav: !prevState.isFav,
            };
        });
    }
```
You will need to hook the `toggleFav` to appropriate event and element in render() method
and also make sure we persist the change to AsyncStorage

You can always submit a "work in progress" PR and so that we could go through actual impelemtation
